document.addEventListener('DOMContentLoaded',async()=>{
 const status=document.getElementById('auth-status'),authView=document.getElementById('auth-view'),accountView=document.getElementById('account-view');let mode='signin';
 const message=(text,error=false)=>{status.textContent=text;status.className=error?'auth-message auth-error':'auth-message';status.hidden=!text};
 const field=(id,label,type='text',attrs='')=>`<div class="field"><label for="${id}">${label}</label><input class="input" id="${id}" name="${id}" type="${type}" ${attrs}></div>`;
 function authForm(){
  if(status.textContent==='Loading your account…')message('');
  if(TNAuthLinkError&&!TNAuth.session)message(TNAuthLinkError,true);
  const signup=mode==='signup',reset=mode==='reset',recovery=TNAuth.recovery;
  authView.classList.remove('hidden');accountView.classList.add('hidden');
  authView.innerHTML=`<div class="auth-layout"><div class="auth-story"><span class="eyebrow">YOUR NEXT DISCOVERY</span><h2>A space for<br>your kind of tech.</h2><p>Save your favourites. Keep your delivery details ready. Find all your orders in one place.</p><img src="assets/catalog/apple-airpods-max-silver-1.webp" alt="AirPods Max headphones"><span>PERSONAL. CONNECTED. YOURS.</span></div><div class="auth-card"><span class="eyebrow">${recovery?'ACCOUNT RECOVERY':signup?'JOIN TECHNEST':'WELCOME TO TECHNEST'}</span><h2>${recovery?'Choose a new password':reset?'Reset your password':signup?'Create your account':'Good to see you again.'}</h2><p class="muted">${recovery?'Set a new password for your account.':reset?'We’ll email you a link to reset your password.':signup?'Your profile and favourites, available wherever you sign in.':'Sign in to your personal TechNest space.'}</p>${!recovery&&!reset?`<div class="auth-tabs"><button type="button" data-mode="signin" class="${!signup?'active':''}">Sign in</button><button type="button" data-mode="signup" class="${signup?'active':''}">Create account</button></div>`:''}<form id="auth-form">${signup?`<div class="form-row">${field('auth-first','First name','text','required maxlength="100" autocomplete="given-name"')}${field('auth-last','Last name','text','required maxlength="100" autocomplete="family-name"')}</div>`:''}${!recovery?field('auth-email','Email address','email','required maxlength="254" autocomplete="email"'):''}${!reset?field('auth-password',recovery?'New password':'Password','password',`required ${signup||recovery?'minlength="8"':''} maxlength="128" autocomplete="${signup||recovery?'new-password':'current-password'}"`):''}${signup||recovery?field('auth-confirm','Confirm password','password','required minlength="8" maxlength="128" autocomplete="new-password"'):''}${signup?'<small class="muted">Use at least 8 characters. We’ll send an email to verify your account.</small>':''}<button class="btn btn-primary btn-block" type="submit">${recovery?'Save new password':reset?'Send reset link':signup?'Create account':'Sign in'} ↗</button></form>${!recovery?`<button class="auth-text-button" id="resend-confirmation" type="button">Resend verification email</button><button class="auth-text-button" data-mode="${reset?'signin':'reset'}">${reset?'Back to sign in':'Forgot your password?'}</button>`:''}<p class="auth-privacy">Your profile is private to your account.</p></div></div>`;
  authView.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;TNAuthLinkError='';message('');authForm()});
  document.getElementById('resend-confirmation')?.addEventListener('click',async e=>{
   const input=document.getElementById('auth-email');if(!input.reportValidity())return;
   const button=e.currentTarget;button.disabled=true;message('Requesting a new verification email…');
   try{const {error}=await TNAuth.client.auth.resend({type:'signup',email:input.value.trim(),options:{emailRedirectTo:location.origin+'/account.html'}});if(error)throw error;message('If this account needs verification, a new email will arrive shortly. Open only the newest confirmation link; older links may no longer work.');}
   catch(error){message(error.message||'Unable to resend the verification email. Please try again later.',true)}finally{button.disabled=false}
  });
  document.getElementById('auth-form').onsubmit=async e=>{
   e.preventDefault();TNAuthLinkError='';const button=e.target.querySelector('[type=submit]');button.disabled=true;message('');
   const email=document.getElementById('auth-email')?.value.trim(),password=document.getElementById('auth-password')?.value;
   try{
    if((signup||recovery)&&password!==document.getElementById('auth-confirm').value)throw new Error('Your passwords don’t match.');
    if(recovery){const {error}=await TNAuth.client.auth.updateUser({password});if(error)throw error;TNAuth.recovery=false;message('Password updated. You’re signed in.');render();}
    else if(reset){const {error}=await TNAuth.client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/account.html'});if(error)throw error;message('If an account exists, a password reset email will arrive shortly.');}
    else if(signup){const {data,error}=await TNAuth.client.auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/account.html',data:{first:document.getElementById('auth-first').value.trim(),last:document.getElementById('auth-last').value.trim()}}});if(error)throw error;if(data.session){await TNAuth.accept(data.session);render();}else{mode='signin';authForm();message('Check your email to confirm your account, then sign in here.');}}
    else{const {data,error}=await TNAuth.client.auth.signInWithPassword({email,password});if(error)throw error;await TNAuth.accept(data.session);if(['checkout','admin'].includes(TNU.params().next)){location.href=TNU.params().next+'.html';return}message('');render();}
   }catch(error){message(error.code==='email_not_confirmed'?'Your email is not confirmed yet. Open the newest confirmation email, or use Resend verification email below.':error.message||'Unable to sign in. Please try again.',true)}finally{button.disabled=false;}
  };
 }
 function render(){
  if(!TNAuth.session||TNAuth.recovery){authForm();return;}
  authView.classList.add('hidden');accountView.classList.remove('hidden');message('');document.getElementById('account-email').textContent=TNAuth.session.user.email;
  const uid=TNAuth.session.user.id;document.getElementById('admin-account-link')?.remove();TNAuth.client.rpc('is_store_admin').then(({data,error})=>{if(!error&&data&&TNAuth.session?.user.id===uid&&!document.getElementById('admin-account-link')){const link=document.createElement('a');link.id='admin-account-link';link.className='btn btn-primary';link.href='admin.html';link.textContent='Manage products ↗';document.querySelector('.account-toolbar').append(link)}});
  const p=TNStore.data.profile||{},form=document.getElementById('profile-panel');
  form.innerHTML=`<div class="profile-heading"><div class="profile-avatar">${TNU.escape((p.first?.[0]||'T')+(p.last?.[0]||'N'))}</div><div><h2>${TNU.escape(p.first?p.first+' '+(p.last||''):'Your profile')}</h2><p class="muted">Saved securely to your TechNest account.</p></div></div><div class="form-row">${profileField('first','First name',p.first,'given-name')}${profileField('last','Last name',p.last,'family-name')}</div><div class="field"><label for="profile-email">Account email</label><input class="input" id="profile-email" value="${TNU.escape(TNAuth.session.user.email)}" readonly></div><div class="form-row">${profileField('phone','Phone',p.phone,'tel')}${profileField('address','Street address',p.address,'street-address')}</div><div class="form-row">${profileField('city','City',p.city,'address-level2')}${profileField('state','State / region',p.state,'address-level1')}</div>${profileField('zip','ZIP / postal code',p.zip,'postal-code')}<button class="btn btn-primary" type="submit">Save profile</button><span class="profile-save-status" role="status"></span>`;
  form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button');b.disabled=true;const note=form.querySelector('.profile-save-status');note.textContent='Saving…';try{await TNAuth.saveProfile(Object.fromEntries(new FormData(form)));note.textContent='Profile saved to your account.';}catch(error){note.textContent=error.message;}finally{b.disabled=false}};
  const orders=TNStore.data.orders;document.getElementById('orders-panel').innerHTML=`<h2>Your orders</h2><p class="muted">Orders placed while signed in are available on every device.</p>${orders.length?orders.map(o=>`<div class="order-card"><div class="order-title"><b>${TNU.escape(o.id)}</b><span class="pill">${TNU.escape(o.status)}</span></div><p class="muted">${TNU.dateLabel(new Date(o.date))} · ${o.items.length} line items</p><div class="order-title"><b>${TNU.money(o.total)}</b><a href="track-order.html?id=${encodeURIComponent(o.id)}" class="btn btn-outline">Track order</a></div></div>`).join(''):'<p class="muted">Your next order will appear here.</p><a class="btn btn-outline" href="shop.html">Explore the store</a>'}`;
  document.getElementById('saved-panel').innerHTML=`<h2>Your saved products</h2><p class="muted">Your favourites follow you wherever you sign in.</p><a class="btn btn-primary" href="wishlist.html">Open wishlist (${TNStore.data.wishlist.length})</a>`;
  const recent=TNStore.data.recent.map(TNU.product).filter(Boolean);document.getElementById('recent-panel').innerHTML=`<h2>Recently viewed</h2>${recent.length?`<div class="product-grid">${recent.map(TNProductCard).join('')}</div>`:'<p class="muted">Explore a product to find it here next time.</p><a class="btn btn-outline" href="shop.html">Start exploring</a>'}`;TNBindProductActions(document.getElementById('recent-panel'));
 }
 function profileField(name,label,value='',autocomplete=''){return `<div class="field"><label for="profile-${name}">${label}</label><input class="input" id="profile-${name}" name="${name}" maxlength="300" autocomplete="${autocomplete}" value="${TNU.escape(value)}"></div>`}
 const buttons=document.querySelectorAll('.account-nav button');buttons.forEach((b,i)=>{b.setAttribute('aria-selected',i===0);b.onclick=()=>{buttons.forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',x===b)});document.querySelectorAll('.account-panel').forEach(x=>x.classList.toggle('hidden',x.id!==b.dataset.panel))};b.onkeydown=e=>{if(['ArrowRight','ArrowDown','ArrowLeft','ArrowUp'].includes(e.key)){e.preventDefault();const next=buttons[(i+(['ArrowRight','ArrowDown'].includes(e.key)?1:buttons.length-1))%buttons.length];next.focus();next.click()}}});
 document.getElementById('sign-out').onclick=async()=>{const b=document.getElementById('sign-out');b.disabled=true;try{const {error}=await TNAuth.client.auth.signOut();if(error)throw error;await TNAuth.accept(null);mode='signin';render();}catch(error){message(error.message,true)}finally{b.disabled=false}};
 document.addEventListener('tn:auth',render);document.addEventListener('tn:auth-error',e=>message(e.detail,true));
 try{await Promise.all([TNAuth.ready,TNBackend.ready]);render();if(TNAuthLinkError)message(TNAuthLinkError,true);}catch(error){authForm();message('Unable to load your account. '+error.message,true)}
});
