document.addEventListener('DOMContentLoaded',()=>{
  document.querySelectorAll('.service-icon').forEach(x=>x.innerHTML=TNIcon(x.dataset.icon,22));
  const slides=[
    {eyebrow:'NEW-SEASON TECHNOLOGY',title:'Bigger catalog. Better choices.',text:'Explore hundreds of phones, laptops, audio products, displays and accessories selected for work, study, travel and entertainment.',cta:'Shop the catalog',link:'shop.html',img:'assets/campaigns/hero-1.jpg'},
    {eyebrow:'SMARTPHONE EVENT',title:'Your next everyday upgrade.',text:'Browse camera-focused phones, 5G devices, vivid displays and long-lasting batteries across multiple price ranges.',cta:'Shop phones',link:'shop.html?category=Phones',img:'assets/campaigns/hero-2.jpg'},
    {eyebrow:'DESK & DISPLAY WEEK',title:'Make your workspace feel complete.',text:'Combine laptops, high-refresh displays, keyboards, hubs and audio gear into a setup that works the way you do.',cta:'Build your setup',link:'shop.html?category=Displays',img:'assets/campaigns/hero-3.jpg'},
    {eyebrow:'AUDIO & GAMING',title:'More immersion. Less clutter.',text:'Wireless audio, headsets, controllers and accessories designed for listening, playing and streaming.',cta:'Explore deals',link:'deals.html',img:'assets/campaigns/hero-4.jpg'}
  ];
  const hero=document.getElementById('hero-slider');
  hero.innerHTML=slides.map((s,i)=>`<section class="hero-slide ${i===0?'active':''}"><div class="hero-slide-bg"><img src="${s.img}" alt="${s.eyebrow}"></div><div class="hero-copy"><span class="hero-mini-badge">${s.eyebrow}</span><h1>${s.title}</h1><p>${s.text}</p><div class="hero-actions"><a href="${s.link}" class="btn btn-primary">${s.cta} ${TNIcon('arrow',17)}</a><a href="deals.html" class="btn btn-outline" style="color:#fff;border-color:#6f8cb4;background:rgba(255,255,255,.08)">View current deals</a></div></div></section>`).join('')+`<div class="hero-dots">${slides.map((_,i)=>`<button class="hero-dot ${i===0?'active':''}" data-slide="${i}" aria-label="Slide ${i+1}"></button>`).join('')}</div>`;
  let ix=0;const set=i=>{ix=i;document.querySelectorAll('.hero-slide').forEach((x,n)=>x.classList.toggle('active',n===i));document.querySelectorAll('.hero-dot').forEach((x,n)=>x.classList.toggle('active',n===i))};document.querySelectorAll('.hero-dot').forEach(b=>b.onclick=()=>set(+b.dataset.slide));setInterval(()=>set((ix+1)%slides.length),6800);
  const cats=[['Phones','phone'],['Laptops','laptop'],['Audio','audio'],['Wearables','watch'],['Tablets','tablet'],['Cameras','camera'],['Gaming','game'],['Accessories','grid'],['Displays','grid']];
  document.getElementById('category-grid').innerHTML=cats.map(([c,i])=>`<a class="category-card reveal" href="shop.html?category=${encodeURIComponent(c)}"><span class="category-icon">${TNIcon(i,27)}</span><strong>${c}</strong><small>${TN_CATEGORY_COUNTS[c]} products</small></a>`).join('');
  const dealPool=TN_PRODUCTS.filter(p=>p.oldPrice).sort((a,b)=>(b.oldPrice-b.price)-(a.oldPrice-a.price)).slice(0,12);
  document.getElementById('deal-products').innerHTML=dealPool.map(TNProductCard).join('');TNBindProductActions(document.getElementById('deal-products'));
  const featured=[...TN_PRODUCTS].sort((a,b)=>(b.rating*100+b.reviews/10)-(a.rating*100+a.reviews/10)).slice(0,10);document.getElementById('featured-products').innerHTML=featured.map(TNProductCard).join('');TNBindProductActions(document.getElementById('featured-products'));
  const newest=[...TN_PRODUCTS].sort((a,b)=>b.arrival-a.arrival).slice(0,12);document.getElementById('new-products').innerHTML=newest.map(TNProductCard).join('');TNBindProductActions(document.getElementById('new-products'));
  const brands=[...new Set(TN_PRODUCTS.map(p=>p.brand))].slice(0,18);document.getElementById('brand-cloud').innerHTML=brands.map(b=>`<a href="shop.html?brand=${encodeURIComponent(b)}">${b}</a>`).join('');
  document.getElementById('stat-products').textContent=TN_PRODUCTS.length+'+';
  const end=new Date(Date.now()+1000*60*60*19+1000*60*43);const timer=document.getElementById('deal-timer');const tick=()=>{let d=Math.max(0,end-Date.now()),h=Math.floor(d/3600000),m=Math.floor((d%3600000)/60000),s=Math.floor((d%60000)/1000);timer.innerHTML=`<span class="time-box"><b>${String(h).padStart(2,'0')}</b><small>HRS</small></span><span class="time-box"><b>${String(m).padStart(2,'0')}</b><small>MIN</small></span><span class="time-box"><b>${String(s).padStart(2,'0')}</b><small>SEC</small></span>`};tick();setInterval(tick,1000);
  const email=document.getElementById('home-newsletter-email');document.getElementById('home-newsletter-btn').onclick=()=>{if(!email.value.includes('@'))return TNToast('Enter a valid email address','error');localStorage.setItem('tn_newsletter',email.value.trim());email.value='';TNToast('You are subscribed to TechNest updates')};
  const splash=document.getElementById('splash');if(sessionStorage.getItem('tn_seen_v3'))splash?.remove();else{sessionStorage.setItem('tn_seen_v3','1');setTimeout(()=>splash?.classList.add('hide'),1000);setTimeout(()=>splash?.remove(),1650)}
});
