document.addEventListener('DOMContentLoaded',async()=>{await TNBackend.ready;
 const p=TNU.params(),state={q:(p.q||'').toLowerCase(),category:p.category||'',brand:p.brand||'',min:0,max:6000,rating:0,sort:'featured',page:1,view:'grid'},pageSize=24;
 document.getElementById('hero-count').textContent=TN_PRODUCTS.length;
 document.getElementById('category-shortcuts').innerHTML=`<a class="subnav-chip" href="shop.html">All ${TN_PRODUCTS.length}</a>`+TN_CATEGORIES.map(c=>`<a class="subnav-chip" href="shop.html?category=${encodeURIComponent(c)}">${c} ${TN_CATEGORY_COUNTS[c]}</a>`).join('');
 const brandSet=[...new Set(TN_PRODUCTS.map(x=>x.brand))].sort();
 document.getElementById('category-filters').innerHTML=TN_CATEGORIES.map(c=>`<label class="check"><input type="radio" name="cat" value="${c}" ${state.category===c?'checked':''}> ${c} <span class="muted">(${TN_CATEGORY_COUNTS[c]})</span></label>`).join('');
 document.querySelector('input[name=cat][value=""]').checked=!state.category;
 document.getElementById('brand-filters').innerHTML=brandSet.map(b=>`<label class="check"><input type="radio" name="brand" value="${b}" ${state.brand===b?'checked':''}> ${b}</label>`).join('');document.querySelector('input[name=brand][value=""]').checked=!state.brand;
 const search=document.getElementById('catalog-search');search.value=p.q||'';
 function filtered(){let a=TN_PRODUCTS.filter(x=>(!state.q||(x.name+' '+x.brand+' '+x.category+' '+x.desc+' '+x.features.join(' ')).toLowerCase().includes(state.q))&&(!state.category||x.category===state.category)&&(!state.brand||x.brand===state.brand)&&x.price>=state.min&&x.price<=state.max&&x.rating>=state.rating);if(state.sort==='price-low')a.sort((x,y)=>x.price-y.price);if(state.sort==='price-high')a.sort((x,y)=>y.price-x.price);if(state.sort==='rating')a.sort((x,y)=>y.rating-x.rating);if(state.sort==='new')a.sort((x,y)=>y.arrival-x.arrival);if(state.sort==='reviews')a.sort((x,y)=>y.reviews-x.reviews);if(state.sort==='featured')a.sort((x,y)=>Number(Boolean(y.badge))-Number(Boolean(x.badge))||y.arrival-x.arrival);return a}
 function renderChips(){const a=[];if(state.q)a.push(['Search',state.q]);if(state.category)a.push(['Category',state.category]);if(state.brand)a.push(['Brand',state.brand]);if(state.rating)a.push(['Rating',state.rating+'+']);if(state.max<6000)a.push(['Price','≤ '+TNU.money(state.max)]);document.getElementById('active-filters').innerHTML=a.map(([k,v])=>`<span class="filter-chip">${k}: ${v}</span>`).join('')+(a.length?`<button class="btn btn-outline" id="clear-all" style="padding:6px 10px;min-height:34px">Clear all</button>`:'');document.getElementById('clear-all')?.addEventListener('click',()=>location.href='shop.html')}
 function renderPagination(total){const pages=Math.max(1,Math.ceil(total/pageSize));if(state.page>pages)state.page=pages;const pg=document.getElementById('pagination');let start=Math.max(1,state.page-2),end=Math.min(pages,start+4);start=Math.max(1,end-4);pg.innerHTML=`<button class="page-btn" ${state.page===1?'disabled':''} data-page="${state.page-1}">‹</button>`+Array.from({length:end-start+1},(_,i)=>start+i).map(n=>`<button class="page-btn ${n===state.page?'active':''}" data-page="${n}">${n}</button>`).join('')+`<button class="page-btn" ${state.page===pages?'disabled':''} data-page="${state.page+1}">›</button>`;pg.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{if(b.disabled)return;state.page=+b.dataset.page;render();scrollTo({top:document.querySelector('.catalog-tools').offsetTop-150,behavior:'smooth'})})}
 function render(){const all=filtered(),start=(state.page-1)*pageSize,a=all.slice(start,start+pageSize);document.getElementById('result-count').textContent=`${all.length} products`;const grid=document.getElementById('catalog-grid');grid.classList.toggle('catalog-list',state.view==='list');grid.innerHTML=a.length?a.map(TNProductCard).join(''):`<div class="no-results" style="grid-column:1/-1"><h3>No products matched your filters</h3><p class="muted">Try clearing a category, brand, price or search filter.</p><button class="btn btn-primary" id="clear-filters">Clear filters</button></div>`;TNBindProductActions(grid);document.getElementById('clear-filters')?.addEventListener('click',()=>location.href='shop.html');renderPagination(all.length);renderChips()}
 search.addEventListener('input',TNU.debounce(()=>{state.q=search.value.trim().toLowerCase();state.page=1;render()}));document.querySelectorAll('input[name=cat]').forEach(x=>x.onchange=()=>{state.category=x.value;state.page=1;render()});document.querySelectorAll('input[name=brand]').forEach(x=>x.onchange=()=>{state.brand=x.value;state.page=1;render()});document.querySelectorAll('input[name=rating]').forEach(x=>x.onchange=()=>{state.rating=+x.value;state.page=1;render()});document.getElementById('price-max').oninput=e=>{state.max=+e.target.value;document.getElementById('price-label').textContent='Up to '+TNU.money(state.max);state.page=1;render()};document.getElementById('sort').onchange=e=>{state.sort=e.target.value;state.page=1;render()};document.getElementById('filter-toggle').onclick=()=>document.getElementById('filters').classList.toggle('show');document.getElementById('grid-view').onclick=()=>{state.view='grid';document.getElementById('grid-view').classList.add('active');document.getElementById('list-view').classList.remove('active');render()};document.getElementById('list-view').onclick=()=>{state.view='list';document.getElementById('list-view').classList.add('active');document.getElementById('grid-view').classList.remove('active');render()};render();
});
