window.TNRenderHeader=function(active=''){
 window.TN_ACTIVE=active;const h=document.getElementById('site-header');if(!h)return;
 const links=[['home','index.html','Home'],['shop','shop.html','Shop all'],['new','new-arrivals.html','Collections'],['brands','brands.html','Brands'],['about','about.html','Our story']];
 h.innerHTML=`<div class="announcement"><div class="container"><span>Thoughtfully chosen tech for work, study and everyday life.</span><span><a href="track-order.html">Track your order</a> &nbsp; / &nbsp; <a href="contact.html">Get in touch</a></span></div></div><header class="site-header"><div class="container header-main"><a href="index.html" class="brand"><span class="brand-mark">${TNIcon('box',23)}</span><span>Tech<b>Nest</b><span style="color:var(--brand)">.</span></span></a><div class="header-search"><div class="search-shell">${TNIcon('search',19)}<input id="global-search" aria-label="Search products" autocomplete="off" placeholder="Search products, brands and more"><span class="muted" style="font-size:11px">Ctrl K</span></div><div class="search-suggestions" id="search-suggestions"></div></div><div class="header-actions"><a class="icon-btn" href="account.html" aria-label="Account">${TNIcon('user')}</a><button class="icon-btn theme-toggle" aria-label="Switch color theme">${TNIcon(TNStore.data.theme==='dark'?'sun':'moon')}</button><a class="icon-btn" href="wishlist.html" aria-label="Wishlist">${TNIcon('heart')}<span class="badge-count wish-count">0</span></a><a class="icon-btn" href="cart.html" aria-label="Cart">${TNIcon('cart')}<span class="badge-count cart-count">0</span></a><button class="icon-btn menu-btn mobile-only" aria-label="Open menu" aria-expanded="false">${TNIcon('menu')}</button></div></div><div class="nav-wrap"><nav class="container nav">${links.map(([key,href,text])=>`<a class="${active===key?'active':''}" href="${href}">${text}</a>`).join('')}<a class="nav-utility" href="support.html">Need a hand?</a><a href="compare.html">Compare</a></nav></div><nav class="container mobile-menu"><div class="search-shell"><input id="mobile-search" aria-label="Search products on mobile" placeholder="Search products"></div>${TN_CATEGORIES.map(c=>`<a href="shop.html?category=${c}">${c}</a>`).join('')}<a href="track-order.html">Track order</a><a href="contact.html">Contact</a></nav></header>`;
 h.querySelector('.menu-btn').onclick=e=>{const menu=h.querySelector('.mobile-menu');menu.classList.toggle('show');e.currentTarget.setAttribute('aria-expanded',menu.classList.contains('show'))};
 h.querySelector('.theme-toggle').onclick=()=>{const t=TNStore.data.theme==='dark'?'light':'dark';TNStore.setTheme(t);document.documentElement.dataset.theme=t;TNRenderHeader(active)};
 const wire=input=>{if(!input)return;input.onkeydown=e=>{if(e.key==='Enter'&&input.value.trim())location.href='shop.html?q='+encodeURIComponent(input.value.trim())};if(input.id==='global-search')input.oninput=TNU.debounce(()=>{const q=input.value.trim().toLowerCase(),box=h.querySelector('#search-suggestions');if(q.length<2){box.classList.remove('show');return}const rows=TN_PRODUCTS.filter(p=>(p.name+' '+p.brand+' '+p.category).toLowerCase().includes(q)).slice(0,5);box.innerHTML=rows.map(p=>`<a class="suggestion" href="product.html?id=${p.id}">${TNU.imgTag(p)}<div><strong>${p.name}</strong><div class="muted">${TNU.money(p.price)}</div></div></a>`).join('')||'<div class="suggestion">No matching products</div>';box.classList.add('show')});};wire(h.querySelector('#global-search'));wire(h.querySelector('#mobile-search'));
 TNUpdateCounts();
};
window.TNUpdateCounts=function(){document.querySelectorAll('.cart-count').forEach(x=>{x.textContent=TNStore.cartCount();x.style.display=TNStore.cartCount()?'grid':'none'});document.querySelectorAll('.wish-count').forEach(x=>{x.textContent=TNStore.data.wishlist.length;x.style.display=TNStore.data.wishlist.length?'grid':'none'})};
window.TNUpdateCompareBar=function(){let b=document.querySelector('.compare-bar');if(!b){b=document.createElement('div');b.className='compare-bar';document.body.appendChild(b)}const ids=TNStore.data.compare;b.classList.toggle('show',ids.length>0);b.innerHTML=`<strong>Compare ${ids.length}/4</strong><div class="compare-list">${ids.map(id=>{const p=TNU.product(id);return p?TNU.imgTag(p,'compare-mini',p.name):''}).join('')}</div><a class="btn btn-primary" href="compare.html">Compare now</a><button class="icon-btn" id="compare-clear">${TNIcon('x',16)}</button>`;const c=document.getElementById('compare-clear');if(c)c.onclick=()=>{TNStore.data.compare=[];TNStore.save();TNUpdateCompareBar()}};
